import * as DocumentPicker from 'expo-document-picker';
import { useRouter } from 'expo-router';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import {
    KeyboardAvoidingView,
    Platform,
    Pressable,
    ScrollView,
    StyleSheet,
    Text,
    TextInput,
    View,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import type { MentioMood } from '@/components/mentio/MentioRobot';
import { MentioScene } from '@/components/mentio/MentioScene';
import { TypingDots } from '@/components/mentio/TypingDots';
import { AGE_BANDS, Mentio } from '@/constants/theme';
import { getTopic } from '@/constants/topics';
import {
    mentioOnDocument,
    mentioOpener,
    mentioRespond,
    type ChatTurn,
    type MentioOutcome,
} from '@/lib/deepseek';
import { loadDocumentText, type LoadDocumentResult, type LoadedDocument } from '@/lib/document';
import { usePreferences } from '@/providers/preferences';

type Message = {
    id: string;
    from: 'mentio' | 'user' | 'system';
    text: string;
};

let idSeq = 0;
const nextId = () => `m${idSeq++}`;

export default function Teach() {
    const router = useRouter();
    const { prefs } = usePreferences();
    const { age, topicId, name } = prefs;

    const topic = useMemo(() => getTopic(topicId), [topicId]);
    const band = AGE_BANDS[age];

    const [messages, setMessages] = useState<Message[]>([]);
    const [draft, setDraft] = useState('');
    const [mood, setMood] = useState<MentioMood>('curious');
    const [typing, setTyping] = useState(false);
    const [reading, setReading] = useState(false);
    const [doc, setDoc] = useState<LoadedDocument | null>(null);
    // Lets the learner retry Mentio's last line if the model couldn't be reached.
    const [retry, setRetry] = useState<(() => Promise<MentioOutcome>) | null>(null);

    const scrollRef = useRef<ScrollView>(null);
    const typingTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
    const alive = useRef(true);

    // The chat so far, mapped to DeepSeek roles (Mentio = assistant, learner = user).
    // Defined before the seeding effect because that effect re-greets on changes.
    const buildHistory = useCallback(
        (): ChatTurn[] =>
            messages
                .filter((m) => m.from === 'mentio' || m.from === 'user')
                .map((m) => ({
                    role: m.from === 'mentio' ? 'assistant' : 'user',
                    content: m.text,
                })),
        [messages]
    );

    const scrollToEnd = useCallback(() => {
        requestAnimationFrame(() => scrollRef.current?.scrollToEnd({ animated: true }));
    }, []);

    /**
     * Mentio never answers instantly. The typing dots show while DeepSeek thinks,
     * and stay up for at least a short beat so the reply never snaps in. `produce`
     * returns an honest outcome: on success we append the model's line; on failure
     * we say so and stash the call so the learner can retry — we never fabricate a
     * reply.
     */
    const respond = useCallback(
        async (produce: () => Promise<MentioOutcome>) => {
            setRetry(null);
            setTyping(true);
            scrollToEnd();

            const minBeat = new Promise<void>((resolve) => {
                typingTimer.current = setTimeout(resolve, 650);
            });

            let outcome: MentioOutcome;
            try {
                const [result] = await Promise.all([produce(), minBeat]);
                outcome = result;
            } catch {
                outcome = { ok: false, error: 'offline' };
            }

            if (!alive.current) return;
            setTyping(false);

            if (outcome.ok) {
                setMood(outcome.reply.mood);
                setMessages((prev) => [
                    ...prev,
                    { id: nextId(), from: 'mentio', text: outcome.reply.text },
                ]);
            } else {
                setMood('curious');
                const note =
                    outcome.error === 'no-key'
                        ? 'Mentio isn’t connected yet — add a DeepSeek API key to wake him up.'
                        : 'Mentio couldn’t reach his brain just now. Check your connection and tap retry.';
                setMessages((prev) => [...prev, { id: nextId(), from: 'system', text: note }]);
                // Only a network problem is worth retrying; a missing key is not.
                if (outcome.error === 'offline') setRetry(() => produce);
            }
            scrollToEnd();
        },
        [scrollToEnd]
    );

    // Seed the conversation: Mentio greets and asks which topic in the subject
    // we'll cover. Generated by the model, like every other line.
    useEffect(() => {
        setMessages([]);
        setDoc(null);
        setMood('curious');
        respond(() => mentioOpener({ age, topicTitle: topic.title, learnerName: name }));
        // Re-greet when the subject or age changes; respond/name are stable enough
        // that including them would only cause a redundant re-greet.
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [topic, age]);

    // Clean up any pending typing timer on unmount.
    useEffect(() => {
        return () => {
            alive.current = false;
            if (typingTimer.current) clearTimeout(typingTimer.current);
        };
    }, []);

    const send = () => {
        const text = draft.trim();
        if (!text || typing || reading) return;
        setDraft('');

        const history = buildHistory();
        setMessages((prev) => [...prev, { id: nextId(), from: 'user', text }]);
        scrollToEnd();

        respond(() =>
            mentioRespond({
                age,
                topicTitle: topic.title,
                history,
                userText: text,
                learnerName: name,
                doc: doc ?? undefined,
            })
        );
    };

    const upload = async () => {
        if (typing || reading) return;

        // Open the picker first; bail quietly if it's dismissed or errors.
        const picked = await (async () => {
            try {
                const result = await DocumentPicker.getDocumentAsync({
                    type: [
                        'text/*',
                        'application/json',
                        'application/pdf',
                        'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                    ],
                    copyToCacheDirectory: true,
                });
                if (result.canceled || !result.assets?.length) return null;
                return result.assets[0];
            } catch {
                return null;
            }
        })();
        if (!picked) return;
        const file = picked;

        // Immediate, visible sign that the upload landed and is being read. PDFs
        // take a moment to parse, so this shows BEFORE the slow extraction starts.
        const statusId = nextId();
        setReading(true);
        setMessages((prev) => [
            ...prev,
            { id: statusId, from: 'system', text: `\u{1F4CE} Reading “${file.name}”…` },
        ]);
        scrollToEnd();

        const history = buildHistory();
        let loaded: LoadDocumentResult;
        try {
            loaded = await loadDocumentText({
                uri: file.uri,
                name: file.name,
                mimeType: file.mimeType,
                size: file.size,
            });
        } catch {
            loaded = { ok: false, reason: 'error' };
        } finally {
            if (alive.current) setReading(false);
        }
        if (!alive.current) return;

        const setStatus = (text: string) =>
            setMessages((prev) => prev.map((m) => (m.id === statusId ? { ...m, text } : m)));

        if (loaded.ok) {
            // Text pulled out — keep it as context so Mentio's questions revolve
            // around the document, and have him open on something specific in it.
            setDoc(loaded.doc);
            setStatus(
                `\u{1F4CE} Studying “${loaded.doc.name}”${loaded.doc.truncated ? ' (first part)' : ''}`
            );
            scrollToEnd();
            respond(() =>
                mentioOnDocument({
                    age,
                    topicTitle: topic.title,
                    history,
                    learnerName: name,
                    file: { name: loaded.doc.name, readable: true, doc: loaded.doc },
                })
            );
        } else {
            // Couldn't read it (scanned PDF, image, empty, or a parse error) — say so
            // plainly, then Mentio asks the learner to explain the material instead.
            const note =
                loaded.reason === 'unsupported'
                    ? `\u{1F4CE} “${file.name}” — I can’t read that file type yet`
                    : loaded.reason === 'empty'
                        ? `\u{1F4CE} “${file.name}” — I couldn’t find any text in it`
                        : `\u{1F4CE} “${file.name}” — I had trouble reading that one`;
            setStatus(note);
            scrollToEnd();
            respond(() =>
                mentioOnDocument({
                    age,
                    topicTitle: topic.title,
                    history,
                    learnerName: name,
                    file: { name: file.name, readable: false },
                })
            );
        }
    };

    return (
        <SafeAreaView style={[styles.safe, { backgroundColor: band.bg }]} edges={['top', 'bottom']}>
            {/* Header */}
            <View style={styles.header}>
                <Pressable onPress={() => router.back()} hitSlop={12} style={styles.back}>
                    <Text style={styles.backText}>‹</Text>
                </Pressable>
                <View style={styles.headerInfo}>
                    <Text style={styles.headerTitle} numberOfLines={1}>
                        {topic.title}
                    </Text>
                    <Text style={styles.headerSub}>
                        {name ? `${name} is teaching Mentio` : 'You’re teaching Mentio'}
                    </Text>
                </View>
            </View>

            {/* Mentio avatar reacting to mood */}
            <View style={styles.avatarRow}>
                <View style={[styles.avatarGlow, { backgroundColor: band.accent, opacity: 0.16 }]} />
                <MentioScene mood={mood} age={age} style={styles.avatar} />
            </View>

            <KeyboardAvoidingView
                style={styles.flex}
                behavior={Platform.OS === 'ios' ? 'padding' : undefined}
                keyboardVerticalOffset={8}>
                {/* Conversation */}
                <ScrollView
                    ref={scrollRef}
                    style={styles.flex}
                    contentContainerStyle={styles.convo}
                    keyboardShouldPersistTaps="handled"
                    onContentSizeChange={scrollToEnd}
                    showsVerticalScrollIndicator={false}>
                    {messages.map((m) => {
                        if (m.from === 'system') {
                            return (
                                <Text key={m.id} style={styles.system}>
                                    {m.text}
                                </Text>
                            );
                        }
                        const mine = m.from === 'user';
                        return (
                            <View
                                key={m.id}
                                style={[styles.bubble, mine ? styles.bubbleMine : styles.bubbleMentio]}>
                                <Text style={[styles.bubbleText, mine && styles.bubbleTextMine]}>{m.text}</Text>
                            </View>
                        );
                    })}

                    {/* Mentio is thinking — bouncing dots before he replies */}
                    {typing && (
                        <View style={[styles.bubble, styles.bubbleMentio, styles.typingBubble]}>
                            <TypingDots color={Mentio.inkSoft} />
                        </View>
                    )}

                    {/* Couldn't reach the model — offer an honest retry instead of faking a reply */}
                    {retry && !typing && (
                        <Pressable
                            onPress={() => {
                                const again = retry;
                                setRetry(null);
                                respond(again);
                            }}
                            style={styles.retryBtn}>
                            <Text style={styles.retryText}>↻  Tap to retry</Text>
                        </Pressable>
                    )}
                </ScrollView>

                {/* Upload hint — nudge the learner to add study material, or show the active doc */}
                <Pressable onPress={upload} style={styles.uploadHint}>
                    <Text style={styles.uploadHintIcon}>📄</Text>
                    <Text style={styles.uploadHintText} numberOfLines={1}>
                        {doc
                            ? `Studying “${doc.name}” — tap to change`
                            : 'Got notes or a worksheet? Upload it so Mentio asks about it.'}
                    </Text>
                </Pressable>

                {/* Input bar */}
                <View style={styles.inputBar}>
                    <Pressable onPress={upload} hitSlop={8} style={styles.uploadBtn}>
                        <Text style={styles.uploadIcon}>＋</Text>
                    </Pressable>
                    <TextInput
                        style={styles.input}
                        value={draft}
                        onChangeText={setDraft}
                        placeholder="Explain it to Mentio…"
                        placeholderTextColor={Mentio.stone}
                        multiline
                        onSubmitEditing={send}
                        returnKeyType="send"
                        blurOnSubmit
                    />
                    <Pressable
                        onPress={send}
                        disabled={!draft.trim()}
                        style={[styles.sendBtn, { backgroundColor: draft.trim() ? Mentio.pine : Mentio.stone }]}>
                        <Text style={styles.sendIcon}>↑</Text>
                    </Pressable>
                </View>
            </KeyboardAvoidingView>
        </SafeAreaView>
    );
}

const styles = StyleSheet.create({
    safe: { flex: 1 },
    flex: { flex: 1 },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingTop: 4,
        paddingBottom: 8,
        gap: 8,
    },
    back: {
        width: 36,
        height: 36,
        borderRadius: 18,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: Mentio.chalk,
        borderWidth: 1,
        borderColor: Mentio.stone,
    },
    backText: {
        fontSize: 24,
        lineHeight: 26,
        fontWeight: '800',
        color: Mentio.ink,
    },
    headerInfo: { flex: 1 },
    headerTitle: {
        fontSize: 18,
        fontWeight: '800',
        color: Mentio.ink,
    },
    headerSub: {
        fontSize: 12.5,
        fontWeight: '600',
        color: Mentio.inkSoft,
    },
    avatarRow: {
        alignItems: 'center',
        justifyContent: 'center',
        height: 150,
    },
    avatarGlow: {
        position: 'absolute',
        width: 150,
        height: 150,
        borderRadius: 75,
    },
    avatar: {
        width: 180,
        height: 150,
    },
    convo: {
        paddingHorizontal: 16,
        paddingBottom: 12,
        gap: 10,
    },
    bubble: {
        maxWidth: '82%',
        paddingHorizontal: 16,
        paddingVertical: 12,
        borderRadius: 18,
    },
    bubbleMentio: {
        alignSelf: 'flex-start',
        backgroundColor: Mentio.chalk,
        borderTopLeftRadius: 6,
        borderWidth: 1,
        borderColor: Mentio.stone,
    },
    bubbleMine: {
        alignSelf: 'flex-end',
        backgroundColor: Mentio.ink,
        borderTopRightRadius: 6,
    },
    bubbleText: {
        fontSize: 15.5,
        lineHeight: 21,
        color: Mentio.ink,
        fontWeight: '600',
    },
    bubbleTextMine: {
        color: Mentio.chalk,
    },
    typingBubble: {
        paddingVertical: 14,
        paddingHorizontal: 18,
    },
    retryBtn: {
        alignSelf: 'center',
        paddingHorizontal: 18,
        paddingVertical: 9,
        borderRadius: 999,
        backgroundColor: Mentio.ink,
    },
    retryText: {
        fontSize: 13.5,
        fontWeight: '800',
        color: Mentio.chalk,
    },
    system: {
        alignSelf: 'center',
        fontSize: 12.5,
        fontWeight: '700',
        color: Mentio.inkSoft,
        backgroundColor: Mentio.sand,
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 999,
        overflow: 'hidden',
    },
    uploadHint: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        marginHorizontal: 16,
        marginBottom: 8,
        paddingHorizontal: 14,
        paddingVertical: 11,
        borderRadius: 14,
        backgroundColor: Mentio.sand,
        borderWidth: 1,
        borderColor: Mentio.stone,
        borderStyle: 'dashed',
    },
    uploadHintIcon: {
        fontSize: 18,
    },
    uploadHintText: {
        flex: 1,
        fontSize: 12.5,
        lineHeight: 17,
        fontWeight: '600',
        color: Mentio.inkSoft,
    },
    inputBar: {
        flexDirection: 'row',
        alignItems: 'flex-end',
        gap: 8,
        paddingHorizontal: 12,
        paddingTop: 8,
        paddingBottom: 6,
        borderTopWidth: 1,
        borderTopColor: Mentio.stone,
    },
    uploadBtn: {
        width: 44,
        height: 44,
        borderRadius: 22,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: Mentio.chalk,
        borderWidth: 1,
        borderColor: Mentio.stone,
    },
    uploadIcon: {
        fontSize: 24,
        lineHeight: 26,
        fontWeight: '700',
        color: Mentio.ink,
    },
    input: {
        flex: 1,
        minHeight: 44,
        maxHeight: 120,
        backgroundColor: Mentio.chalk,
        borderRadius: 22,
        paddingHorizontal: 16,
        paddingTop: 11,
        paddingBottom: 11,
        fontSize: 15.5,
        color: Mentio.ink,
        borderWidth: 1,
        borderColor: Mentio.stone,
    },
    sendBtn: {
        width: 44,
        height: 44,
        borderRadius: 22,
        alignItems: 'center',
        justifyContent: 'center',
    },
    sendIcon: {
        fontSize: 22,
        fontWeight: '800',
        color: Mentio.chalk,
    },
});
